import LowWeight.SAT.Pure4
import LowWeight.SAT.One4
import LowWeight.SAT.Pure5
import LowWeight.SAT.One5
import LowWeight.SAT.Same5
import LowWeight.SAT.Chain5
import LowWeight.SAT.Disj5
import LowWeight.SAT.Pure6
import LowWeight.SAT.One6
import LowWeight.SAT.Same6
import LowWeight.SAT.Chain6
import LowWeight.SAT.Disj6
import LowWeight.SAT.Gen6_3
import LowWeight.SAT.Pure7
import LowWeight.SAT.One7
import LowWeight.SAT.Same7
import LowWeight.SAT.Chain7
import LowWeight.SAT.Disj7
import LowWeight.SAT.Gen7_3
import LowWeight.SAT.Gen7_4
import LowWeight.SAT.Pure8
import LowWeight.SAT.One8
import LowWeight.SAT.Same8
import LowWeight.SAT.Chain8
import LowWeight.SAT.Disj8
import LowWeight.SAT.Gen8_3
import LowWeight.SAT.Gen8_4
import LowWeight.SAT.Gen8_5
import LowWeight.SAT.Pure9
import LowWeight.SAT.One9
import LowWeight.SAT.Same9
import LowWeight.SAT.Chain9
import LowWeight.SAT.Disj9
import LowWeight.SAT.Gen9_3
import LowWeight.SAT.Gen9_4
import LowWeight.SAT.Gen9_5
import LowWeight.SAT.Gen9_6
import LowWeight.SAT.Pure10
import LowWeight.SAT.One10
import LowWeight.SAT.Same10
import LowWeight.SAT.Chain10
import LowWeight.SAT.Disj10
import LowWeight.SAT.Gen10_3
import LowWeight.SAT.Gen10_4
import LowWeight.SAT.Gen10_5
import LowWeight.SAT.Gen10_6
import LowWeight.SAT.Gen10_7
import LowWeight.SAT.Pure11
import LowWeight.SAT.One11
import LowWeight.SAT.Same11
import LowWeight.SAT.Chain11
import LowWeight.SAT.Disj11
import LowWeight.SAT.Gen11_3
import LowWeight.SAT.Gen11_4
import LowWeight.SAT.Gen11_5
import LowWeight.SAT.Gen11_6
import LowWeight.SAT.Gen11_7
import LowWeight.SAT.Gen11_8
import LowWeight.SAT.Same4
import LowWeight.SAT.Chain4
import LowWeight.SAT.Disj4
